### ISSUE TITLE
🕹️ [FEAT] - <숫자 야구게임 학습 테스트 실습>

### ISSUE THREAD

**Issue by LeeJuHwan** [java-playground-hiking/java-baseball#4]
### Missions

⚾️ 숫자 야구게임

### ✅ Tasks
---
> String 클래스에 대한 학습 테스트
- [x] 요구사항 1
- [x] 요구사항 2
- [x] 요구사항 3

> Set Collection에 대한 학습 테스트
- [x] 요구사항 1
- [x] 요구사항 2
- [x] 요구사항 3

### Confirmation

- [X] 프로젝트를 지정 했습니다.
- [X] 담당자를 지정 했습니다.
- [X] 라벨을 지정 했습니다.
