### ISSUE TITLE
🕹️ [FEAT] - <문자열 계산기 구현 및 테스트 케이스 작성>

### ISSUE THREAD

**Issue by LeeJuHwan** [java-playground-hiking/java-baseball#6]
### Missions

⚾️ 숫자 야구게임

### ✅ Tasks
---
- [x] 사용자가 입력한 값에 따라 사칙 연산을 수행 하는 계산기 구현
- [x] 연산자 우선 순위가 아닌, 입력한 우선 순위로 계산
- [x] 서비스 계층에서 관심사가 다른 객체 관리 로직 -> 객체 분리
- [x] 테스트 케이스 작성

### Confirmation

- [X] 프로젝트를 지정 했습니다.
- [X] 담당자를 지정 했습니다.
- [X] 라벨을 지정 했습니다.
